// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNhzstxT43fiiFGPjugSbtTgzeDnQrIbA',
    appId: '1:189381920997:web:c98135fb07ef069e1fec0c',
    messagingSenderId: '189381920997',
    projectId: 'store-291d5',
    authDomain: 'store-291d5.firebaseapp.com',
    storageBucket: 'store-291d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkRiFIWAZ6n6DUsevbC_HduQfcaOCqCdo',
    appId: '1:189381920997:android:e718130d8717b8e41fec0c',
    messagingSenderId: '189381920997',
    projectId: 'store-291d5',
    storageBucket: 'store-291d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwaYC71Jez0pyyU4uKaxnnC8DTH1-UBhY',
    appId: '1:189381920997:ios:e0095449f88cc0821fec0c',
    messagingSenderId: '189381920997',
    projectId: 'store-291d5',
    storageBucket: 'store-291d5.appspot.com',
    iosClientId: '189381920997-8g0ep5bgvi5avvsphqi16hrj9k1jc55p.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwaYC71Jez0pyyU4uKaxnnC8DTH1-UBhY',
    appId: '1:189381920997:ios:7cc7dad10ce4ce401fec0c',
    messagingSenderId: '189381920997',
    projectId: 'store-291d5',
    storageBucket: 'store-291d5.appspot.com',
    iosClientId: '189381920997-5oc7okvtftomt8e82ice4an21pichcia.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0.RunnerTests',
  );
}
